# -*- coding: utf-8 -*-

standardGL = {
	"B": [["D", True, 0], ["E", True, 0], ["H", False, 0], ["P", True, 0], ["R", False, 0], ["Germandbls", False, 0], ["germandbls", False, 0], ["three", False, 0], ["eight", False, 0]],
	"C": [["D", False, 0], ["G", True, 0], ["O", True, 0], ["Q", False, 0]],
	"D": [["B", False, 0], ["C", False, 0], ["E", False, 0], ["G", False, 0], ["O", True, 0], ["Q", False, 0]],
	"E": [["B", True, 0], ["D", False, 0], ["F", True, 0], ["H", False, 0]],
	"F": [["E", True, 0], ["H", False, 0]],
	"G": [["A", False, 0], ["C", False, 0], ["D", False, 0], ["H", False, 0], ["O", True, 0], ["Q", False, 0], ["x", False, 0]],
	"H": [["B", False, 0], ["D", False, 0], ["E", False, 0], ["F", False, 0], ["I", False, 0], ["J", False, 0], ["K", False, 0], ["L", False, 0], ["M", False, 0], ["N", True, 0], ["P", False, 0], ["R", False, 0], ["U", True, 0]],
	"I": [["B", False, 0], ["D", False, 0], ["E", False, 0], ["F", False, 0], ["H", False, 0], ["J", False, 0], ["K", False, 0], ["L", False, 0], ["M", False, 0], ["N", False, 0], ["P", False, 0], ["R", False, 0], ["T", True, 0], ["U", False, 0], ["Y", True, 0], ["i", False, 0], ["l", True, 0], ["one", True, 0]],
	"J": [["I", True, 0], ["U", False, 0]],
	"K": [["B", False, 0], ["H", False, 0], ["I", True, 0], ["R", False, 0], ["X", False, 0], ["Y", False, 0]],
	"L": [["E", False, 0], ["H", False, 0], ["I", True, 0]],
	"M": [["H", True, 0], ["I", False, 0], ["O", False, 0], ["N", False, 0], ["V", False, 0], ["W", False, 0]],
	"N": [["H", True, 0], ["I", False, 0], ["M", False, 0], ["U", True, 0]],
	"O": [["C", True, 0], ["D", False, 0], ["G", True, 0], ["Q", True, 0], ["zero", True, 0]],
	"P": [["B", True, 0], ["F", True, 0], ["R", True, 0]],
	"Q": [["C", False, 0], ["D", False, 0], ["G", False, 0], ["O", True, 0], ["R", False, 0]],
	"R": [["B", False, 0], ["F", False, 0], ["P", True, 0], ["Q", False, 0], ["X", False, 0]],
	"T": [["H", False, 0], ["I", True, 0], ["Y", True, 0]],
	"U": [["H", False, 0], ["N", True, 0], ["O", False, 0], ["V", False, 0]],
	"V": [["U", True, 0], ["W", False, 0], ["X", False, 0], ["Y", True, 0]],
	"W": [["M", False, 0], ["V", False, 0]],
	"X": [["K", False, 0], ["N", False, 0], ["R", False, 0], ["V", False, 0], ["Y", True, 0], ["Z", True, 0]],
	"Y": [["I", False, 0], ["T", True, 0], ["U", False, 0], ["V", True, 0], ["W", False, 0], ["X", False, 0]],
	"Z": [["L", False, 0], ["T", False, 0], ["X", False, 0]],
	"AE": [["A", True, 0], ["E", True, 0], ["OE", True, 0]],
	"IJ": [["I", False, 0], ["J", True, 0], ["U", True, 0]],
	"Eng": [["N", True, 0], ["j", True, 0]],
	"Oslash": [["O", True, 0], ["Q", False, 0]],
	"OE": [["E", True, 0], ["O", True, 0], ["OE", True, 0]],
	"Thorn": [["D", False, 0], ["H", False, 0], ["I", False, 0], ["P", True, 0]],
	"Germandbls": [["B", True, 0], ["S", True, 0], ["T", False, 0], ["germandbls", False, 0]],
	"b": [["c", False, 0], ["e", False, 0], ["h", True, 0], ["k", False, 0], ["l", False, 0], ["o", True, 0], ["p", True, 0]],
	"c": [["b", False, 0], ["d", False, 0], ["e", True, 0], ["g", False, 0], ["o", True, 0], ["p", False, 0], ["q", False, 0]],
	"d": [["c", False, 0], ["eth", False, 0], ["e", False, 0], ["l", False, 0], ["o", True, 0], ["q", True, 0]],
	"e": [["b", False, 0], ["c", True, 0], ["d", False, 0], ["g", False, 0], ["o", True, 0], ["p", False, 0], ["q", False, 0]],
	"f": [["l", False, 0], ["longs", False, 0], ["germandbls", False, 0], ["t", True, 0]],
	"g": [["c", False, 0], ["e", False, 0], ["o", True, 0], ["q", False, 0]],
	"h": [["b", True, 0], ["k", False, 0], ["l", False, 0], ["m", False, 0], ["n", True, 0], ["r", False, 0]],
	"i": [["I", False, 0], ["j", True, 0], ["l", True, 0], ["n", False, 0]],
	"j": [["i", True, 0], ["l", False, 0], ["n", False, 0]],
	"k": [["b", True, 0], ["h", False, 0], ["l", False, 0], ["x", True, 0]],
	"l": [["I", True, 0], ["b", False, 0], ["h", False, 0], ["k", False, 0], ["i", False, 0], ["one", True, 0]],
	"m": [["h", False, 0], ["n", True, 0], ["r", False, 0], ["w", False, 0]],
	"n": [["h", False, 0], ["m", False, 0], ["r", False, 0], ["u", True, 0], ["v", False, 0]],
	"o": [["b", False, 0], ["c", True, 0], ["d", False, 0], ["eth", False, 0], ["e", True, 0], ["g", False, 0], ["p", False, 0], ["q", False, 0]],
	"p": [["b", True, 0], ["c", False, 0], ["e", False, 0], ["n", False, 0], ["o", True, 0]],
	"q": [["d", True, 0], ["c", False, 0], ["e", False, 0], ["g", False, 0], ["o", True, 0]],
	"r": [["h", False, 0], ["m", False, 0], ["n", True, 0]],
	"t": [["f", True, 0], ["l", False, 0]],
	"u": [["n", True, 0], ["v", False, 0]],
	"v": [["n", False, 0], ["w", False, 0], ["x", False, 0], ["y", True, 0]],
	"w": [["v", False, 0], ["m", False, 0]],
	"x": [["k", True, 0], ["v", False, 0], ["z", False, 0]],
	"y": [["v", True, 0]],
	"z": [["x", False, 0]],
	"ae": [["a", True, 0], ["e", True, 0], ["o", False, 0], ["oe", True, 0]],
	"eth": [["d", True, 0], ["o", True, 0]],
	"idotless": [["I", False, 0], ["i", False, 0], ["j", False, 0], ["uni0237", False, 0], ["l", True, 0], ["n", False, 0]],
	"uni0237": [["i", False, 0], ["idotless", True, 0], ["l", False, 0], ["n", False, 0]],
	"eng": [["j", True, 0], ["m", False, 0], ["n", True, 0]],
	"oslash": [["o", True, 0]],
	"oe": [["ae", True, 0], ["e", True, 0], ["o", True, 0]],
	"germandbls": [["B", True, 0], ["b", False, 0], ["f", True, 0], ["s", True, 0], ["longs", True, 0]],
	"longs": [["f", True, 0], ["l", False, 0], ["germandbls", False, 0]],
	"thorn": [["b", True, 0], ["h", True, 0], ["p", True, 0]],
	"zero": [["O", True, 0]],
	"one": [["I", True, 0], ["l", True, 0]],
	"two": [["question", True, 0]],
	"three": [["B", False, 0], ["eight", True, 0]],
	"five": [["six", True, 0]],
	"six": [["zero", True, 0], ["five", True, 0], ["eight", True, 0], ["nine", False, 0]],
	"seven": [["T", False, 0]],
	"eight": [["B", False, 0], ["zero", True, 0], ["three", True, 0], ["six", False, 0], ["nine", False, 0]],
	"nine": [["zero", True, 0], ["six", True, 0], ["eight", True, 0]],
	"question": [["two", True, 0], ["period", True, 0], ["exclam", True, 0]],
	"exclam": [["I", True, 0], ["T", False, 0], ["one", False, 0], ["period", True, 0], ["question", True, 0]],
	"cent": [["c", True, 0]],
	"dollar": [["S", True, 0]],
	"euro": [["C", True, 0]],
	"florin": [["f", True, 0]],
	"franc": [["F", True, 0]],
	"uni20B9": [["R", True, 0]],
	"uni20BD": [["P", True, 0]],
	"uni20BF": [["B", True, 0]],
	"yen": [["Y", True, 0]],
	"product": [["H", True, 0]],
	"mu": [["u", True, 0]],
	"at": [["a", True, 0]],
	"ampersand": [["E", False, 0], ["t", False, 0]],
	"estimated": [["e", False, 0]]
}
